Update detekt.yaml

diff --git a/.github/workflows/detekt.yaml b/.github/workflows/detekt.yaml
--- a/.github/workflows/detekt.yaml
+++ b/.github/workflows/detekt.yaml
@@ -1,23 +1,31 @@
-name: ktlint
+name: detekt
 
 on:
   push:
     paths:
       - "**/*.kt"
-      - ".github/workflows/ktlint.yml"
+      - ".github/workflows/detekt.yml"
 jobs:
-  ktlint:
+  without-type-resolution:
     runs-on: ubuntu-latest
-
+    env:
+      GRADLE_OPTS: -Dorg.gradle.daemon=false
     steps:
-      - name: "checkout"
-        uses: actions/checkout@v2
+      - name: Checkout Repo
+        uses: actions/checkout@v3
 
-      - name: detekt
+      - name: Setup Java
+        uses: actions/setup-java@v3
+        with:
+          java-version: 11
+
+      - name: Run detekt
         run: ./gradlew detekt
 
-      - name: Get date
-        id: info
-        run: |
-          : # Get current date (YYMMDD)
-          echo "::set-output name=date::$(date +'%Y%m%d')"
+      # Make sure we always run this upload task,
+      # because the previous step may fail if there are findings.
+      - name: Upload SARIF to GitHub using the upload-sarif action
+        uses: github/codeql-action/upload-sarif@v2
+        if: success() || failure()
+        with:
+          sarif_file: build/reports/detekt/detekt.sarif
